apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: "jmkub-f1a8"
    labels:
        app: "jmkub-f1a8"
    annotations:
        kubernetes.io/ingress.class: addon-http-application-routing
spec:
    rules:
        - host: default-jmkub-f1a8.ffacf203d2ec42f787b4.eastus.aksapp.io
          http:
            paths:
            - path: /
              backend:
                serviceName: "jmkub-f1a8"
                servicePort: 80